
name: Deploy Azure Infrastructure with Terraform

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment: dev or staging'
        required: true

jobs:
  terraform:
    name: 'Terraform on Azure'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env }}
    defaults:
      run:
        working-directory: .  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure/login@24848bc889cfc0a8313c2b3e378ac0d625b9bc16
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
     
    - name: Set Azure Subscription
      env:
        subscriptionId: "cb3e902d-604f-41a5-9297-c0f6a596a9f7"
      run: |
          az account set --subscription $subscriptionId
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Initialize
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="${{ github.event.inputs.env }}.tfvars"

    # - name: Terraform Apply
    #   run: terraform apply -var-file="${{ github.event.inputs.env }}.tfvars" -auto-approve
